### ISSUE TITLE
Clarify auto-upgrade behavior?

### ISSUE THREAD

**Issue by jab** [RobertCraigie/pyright-python#117]
I am looking into using this project to run pyright as a pre-commit hook.

https://github.com/RobertCraigie/pyright-python/#readme currently says:

> We also automatically upgrade the pyright npm package to its latest version on every run, see below for how to change this behaviour.

But the next sentence says:

> By default Pyright for Python is set to target a specific pyright version...

These two sentences seem to contradict each other?

Is the default behavior the latter, i.e. to pin to a specific pyright version, so as to not defeat reproducible CI, and let users run `pre-commit autoupdate` as usual when they want to upgrade so they can do so in a controlled fashion? If so, then what is the first sentence trying to say?

Thanks for clarifying, and for maintaining this project.

**Comment by RobertCraigie** [comment]
Hey @jab, thanks for reporting this. You're completely right the documentation is contradictory in that aspect.

The actual behaviour is the latter, Pyright for Python is pinned to a specific Pyright version which you can change by setting the environment variable `PYRIGHT_PYTHON_FORCE_VERSION` to `latest` or to a specific version.

We did previously automatically upgrade Pyright to the latest version but as you mentioned this makes CI not reproducible which is why that behaviour was changed.
