### ISSUE TITLE
Any potential issues running this with `asdf`?

### ISSUE THREAD

**Issue by kkom** [RobertCraigie/pyright-python#139]
👋 @RobertCraigie – we're using Typescript and Python in our company and managing all the language runtimes with `asdf`.

Are you aware of `asdf`? If yes, can you foresee any potential issues if we were to start using `pyright-python` alongside `asdf`-managed Node.js? I'm just being extra cautious now because I desperately want to avoid messing our developers' Node environment.

PS: Our `.tool-versions` file looks like this right now:

```
# Node.js
nodejs 16.17.1
pnpm 7.17.1

# Python
poetry 1.3.2
python 3.11.1
```

**Comment by RobertCraigie** [comment]
Hey @kkom! No I haven't heard of `asdf` before but I can fairly confidently say that it shouldn't cause any issues. This library doesn't mess with existing installations of Node or the user's environment at all.

For example, even if we need to download a node binary for you, it is not made available on your machine, we just download the binary and use `npx` to run `pyright` (I am just about to change this to instead use `npm install` and a separate `node run` fwiw) so unless `npx` does weird things under the hood then it should be completely fine.

In the case where Node is already installed on the user's machine then this library is essentially just a very thin wrapper over `npx pyright@version` and doesn't really do anything else that would cause foreseeable issues.

**Comment by kkom** [comment]
Thank you! We will give it a try then. :) I assume that the change you mention should be transparent to us, or is there any reason to wait for it (eg the old method may have some leftover assets, etc)?

**Comment by RobertCraigie** [comment]
Yeah the goal with changing the internal method is to support offline usage as `npx` doesn't seem to cache packages and will always reinstall the package. It should be a completely transparent change and I can't see any benefits in waiting.

The current method stores assets in a temporary directory so any leftover assets should be removed when you restart your machine. For what it's worth, the new method will respect `$XDG_CACHE_HOME` and otherwise default to `~/.cache`.
